spring:
  cloud:
    stream:
      bindings:
        input1:
          content-type: text/plain
          destination: test-topic
          group: test-group1
        input2:
          consumer:
            concurrency: 20
          content-type: text/plain
          destination: test-topic
          group: test-group2
        output:
          content-type: application/json
          destination: test-topic
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          input1:
            consumer:
              orderly: true
          input2:
            consumer:
              orderly: false
              tags: tagStr
