server:
  port: 9010
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          lowerCaseServiceId: true
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: http://47.97.192.128/:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

