spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: business
          uri: http://127.0.0.1:10200
          order: 0
          predicates:
            - Path=/business-social/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # 令牌产生效率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的容量
                redis-rate-limiter.burstCapacity: 2
                key-resolver: "#{@apiKeyResolver}"
# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug
#server:
#  port: 9010
