spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: business-social
          uri: lb://business-social
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
            - Path=/business-social/**
          filters:
            - StripPrefix=1
# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug
