spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.192.128:8848
        metadata:
          name: authUser
      config:
        group: DEFAULT_GROUP
        prefix: auth-user
        file-extension: yml
        server-addr: 47.97.192.128:8848
       # shared-dataids: redis.yaml,mysql.yaml

