dubbo:
  scan:
    base-packages: com.sy.spring.cloud.alibaba.business.goods.dubbo
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: alibaba-dubbo-server

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
