dubbo:
  scan:
    base-packages: com.sy.spring.cloud.alibaba.business.goods.dubbo
  protocols:
    dubbo:
      name: dubbo
      port: -1
  protocol:
    serialization: kryo
  # 关闭依赖关系
  consumer:
    check: true
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: alibaba-dubbo-server

feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
