dubbo:
  consumer:
    check: false
  cloud:
    subscribed-services: business-goods
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

spring:
  cloud:
    stream:
      bindings:
        input1:
          content-type: text/plain
          destination: test-topic
          group: test-group1
        input2:
          consumer:
            concurrency: 20
          content-type: text/plain
          destination: test-topic
          group: test-group2
        output:
          content-type: application/json
          destination: test-topic
      rocketmq:
        binder:
          name-server: 123.57.34.92:9876
